AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  AwsNamespace:
    Type: String
    Description: Used to generate namespaced AWS resources
Resources:
  ApiGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: apigateway.amazonaws.com
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonApiGatewayPushToCloudWatchLogs
  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayRole.Arn
  ApiGateway:
    Type: AWS::Serverless::Api
    DependsOn:
      - ApiGatewayAccount
    Properties:
      StageName: !Sub "development"
      Name: cicd-pipeline-java
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
  LambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub cicd-pipeline-basic-java-function
      Handler: helloworld.App::handleRequest
      Runtime: java8
      CodeUri: ../HelloWorldFunction/target/HelloWorld-1.0.jar
      MemorySize: 192
      Timeout: 30
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
                - "ssm:DescribeParameters"
                - "ssm:PutParameter"
                - "ssm:GetParameterHistory"
                - "ssm:GetParametersByPath"
                - "ssm:GetParameters"
                - "ssm:GetParameter"
              Resource: '*'
      Events:
        Post:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId:
              Ref: ApiGateway
Outputs:
  Url:
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/development/"
    Export:
      Name: !Sub ${AWS::StackName}-url
