AWSTemplateFormatVersion: '2010-09-09'

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub test-cicd-webhook-builder-bucket-java
      AccessControl: AuthenticatedRead
